[2024-11-16T04:46:07.998+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T04:46:08.015+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing.hello manual__2024-11-16T04:46:04.808072+00:00 [queued]>
[2024-11-16T04:46:08.023+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing.hello manual__2024-11-16T04:46:04.808072+00:00 [queued]>
[2024-11-16T04:46:08.024+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-16T04:46:08.040+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): hello> on 2024-11-16 04:46:04.808072+00:00
[2024-11-16T04:46:08.052+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-16T04:46:08.052+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'testing', 'hello', 'manual__2024-11-16T04:46:04.808072+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpy6licw8p']
[2024-11-16T04:46:08.053+0000] {standard_task_runner.py:72} INFO - Started process 4474 to run task
[2024-11-16T04:46:08.054+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask hello
[2024-11-16T04:46:08.109+0000] {task_command.py:467} INFO - Running <TaskInstance: testing.hello manual__2024-11-16T04:46:04.808072+00:00 [running]> on host 295fa4341010
[2024-11-16T04:46:08.199+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T04:46:04.808072+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T04:46:04.808072+00:00'
[2024-11-16T04:46:08.201+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T04:46:08.201+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T04:46:08.202+0000] {logging_mixin.py:190} INFO - Current task name:hello state:running start_date:2024-11-16 04:46:08.016392+00:00
[2024-11-16T04:46:08.202+0000] {logging_mixin.py:190} INFO - Dag name:testing and current dag run status:running
[2024-11-16T04:46:08.203+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T04:46:16.103+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:16.261+0000] {logging_mixin.py:190} INFO - Header extracted
[2024-11-16T04:46:16.691+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:18.751+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:19.344+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:21.385+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:21.805+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:23.838+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:24.231+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:26.265+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:26.460+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:27.188+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:27.418+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:29.453+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:29.645+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:31.677+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:31.854+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:33.885+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:34.093+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:36.122+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:36.312+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:38.338+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:38.521+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:40.542+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:40.742+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:42.771+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:42.963+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:44.985+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:45.191+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:47.211+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:47.382+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:49.404+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:46:49.584+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T04:46:51.609+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T04:47:10.849+0000] {logging_mixin.py:190} INFO - No more pages or 'Next' button not clickable.
[2024-11-16T04:47:10.957+0000] {logging_mixin.py:190} INFO - data extracted successfully
[2024-11-16T04:47:10.960+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/etl/extract.py", line 74, in extract
    date_str = date_text.replace("As of ", "").split(",")[0] + "," + scraping_date.split(',')[1]
                                                                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
[2024-11-16T04:47:10.995+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-16T04:47:10.996+0000] {logging_mixin.py:190} INFO - Task start:2024-11-16 04:46:08.016392+00:00 end:2024-11-16 04:47:10.994674+00:00 duration:62.978282
[2024-11-16T04:47:10.997+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): hello> dag:<DAG: testing> dagrun:<DagRun testing @ 2024-11-16 04:46:04.808072+00:00: manual__2024-11-16T04:46:04.808072+00:00, state:running, queued_at: 2024-11-16 04:46:04.875072+00:00. externally triggered: True>
[2024-11-16T04:47:10.998+0000] {logging_mixin.py:190} INFO - Failure caused by 'list' object has no attribute 'split'
[2024-11-16T04:47:10.999+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=testing, task_id=hello, run_id=manual__2024-11-16T04:46:04.808072+00:00, execution_date=20241116T044604, start_date=20241116T044608, end_date=20241116T044710
[2024-11-16T04:47:11.028+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T04:47:11.029+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 70 for task hello ('list' object has no attribute 'split'; 4474)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/etl/extract.py", line 74, in extract
    date_str = date_text.replace("As of ", "").split(",")[0] + "," + scraping_date.split(',')[1]
                                                                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
[2024-11-16T04:47:11.056+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-16T04:47:11.077+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T04:47:11.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
