[2024-11-16T06:42:16.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T06:42:16.493+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing.hello manual__2024-11-16T06:42:08.006223+00:00 [queued]>
[2024-11-16T06:42:16.520+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing.hello manual__2024-11-16T06:42:08.006223+00:00 [queued]>
[2024-11-16T06:42:16.521+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-16T06:42:16.577+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): hello> on 2024-11-16 06:42:08.006223+00:00
[2024-11-16T06:42:16.619+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=16103) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-16T06:42:16.619+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'testing', 'hello', 'manual__2024-11-16T06:42:08.006223+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpnpy64hlj']
[2024-11-16T06:42:16.625+0000] {standard_task_runner.py:72} INFO - Started process 16219 to run task
[2024-11-16T06:42:16.625+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask hello
[2024-11-16T06:42:17.311+0000] {task_command.py:467} INFO - Running <TaskInstance: testing.hello manual__2024-11-16T06:42:08.006223+00:00 [running]> on host 295fa4341010
[2024-11-16T06:42:17.577+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T06:42:08.006223+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-16T06:42:08.006223+00:00'
[2024-11-16T06:42:17.580+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T06:42:17.582+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T06:42:17.584+0000] {logging_mixin.py:190} INFO - Current task name:hello state:running start_date:2024-11-16 06:42:16.496606+00:00
[2024-11-16T06:42:17.585+0000] {logging_mixin.py:190} INFO - Dag name:testing and current dag run status:running
[2024-11-16T06:42:17.586+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T06:42:24.998+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:25.075+0000] {logging_mixin.py:190} INFO - Header extracted
[2024-11-16T06:42:25.376+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:27.411+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:27.726+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:29.766+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:30.070+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:32.136+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:32.806+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:34.858+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:35.231+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:37.262+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:37.536+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:38.109+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:38.388+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:40.421+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:40.694+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:42.728+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:43.021+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:45.055+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:45.343+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:47.377+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:47.732+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:49.765+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:50.038+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:52.079+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:52.427+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:54.463+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:54.759+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:56.814+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:57.110+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:42:59.145+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:42:59.427+0000] {logging_mixin.py:190} INFO - Next button clicked
[2024-11-16T06:43:01.460+0000] {logging_mixin.py:190} INFO - Table located
[2024-11-16T06:43:20.200+0000] {logging_mixin.py:190} INFO - No more pages or 'Next' button not clickable.
[2024-11-16T06:43:20.289+0000] {logging_mixin.py:190} INFO - data extracted successfully
[2024-11-16T06:43:20.293+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/etl/extract.py", line 75, in extract
    formatted_date = datetime.strptime(date_str, "%b %d %Y").strftime("%Y-%m-%d")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Nov 14, 2024' does not match format '%b %d %Y'
[2024-11-16T06:43:20.412+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-16T06:43:20.413+0000] {logging_mixin.py:190} INFO - Task start:2024-11-16 06:42:16.496606+00:00 end:2024-11-16 06:43:20.411607+00:00 duration:63.915001
[2024-11-16T06:43:20.415+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): hello> dag:<DAG: testing> dagrun:<DagRun testing @ 2024-11-16 06:42:08.006223+00:00: manual__2024-11-16T06:42:08.006223+00:00, state:running, queued_at: 2024-11-16 06:42:08.303629+00:00. externally triggered: True>
[2024-11-16T06:43:20.416+0000] {logging_mixin.py:190} INFO - Failure caused by time data 'Nov 14, 2024' does not match format '%b %d %Y'
[2024-11-16T06:43:20.417+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=testing, task_id=hello, run_id=manual__2024-11-16T06:42:08.006223+00:00, execution_date=20241116T064208, start_date=20241116T064216, end_date=20241116T064320
[2024-11-16T06:43:20.445+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T06:43:20.446+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task hello (time data 'Nov 14, 2024' does not match format '%b %d %Y'; 16219)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/etl/extract.py", line 75, in extract
    formatted_date = datetime.strptime(date_str, "%b %d %Y").strftime("%Y-%m-%d")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Nov 14, 2024' does not match format '%b %d %Y'
[2024-11-16T06:43:20.486+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-16T06:43:20.513+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T06:43:20.518+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
